### ISSUE TITLE
Serato support?

### ISSUE THREAD

**Issue by Fred-DTV** [Creepercdn/now_playing#2]
hey hey,

Is there a way to have a Serato integration for this amazing script?

Serato offers a live playlist online https://serato.com/playlists/browse/genres/live

This would allow DJs to integrate the tracks into their live streams

**Comment by rsp4jack** [comment]
Okay, I will try it.

**Comment by rsp4jack** [comment]
Do you want to display song name sync by time since playlist?

**Comment by rsp4jack** [comment]
I think song name is displayed at absolute time (such as 3:15 p.m.)
Thank you for your report.

**Comment by rsp4jack** [comment]
Maybe I will add a function to set start time to now (For example, Serato says start at 1.35 p.m., but now is 2.35 p.m., so can set start time to 2:35 p.m.).

**Comment by Fred-DTV** [comment]
Hey @Creepercdn 

Sorry for the late reply, we had a ton of work the last couple of days

After posting this I've actually found this: https://github.com/e1miran/Now-Playing-Serato
Which works pretty well, the only downside is, that it is an extra app. 

Sorry if you've already put work into this

**Comment by rsp4jack** [comment]
Thank you very much. I will integrate it.

**Comment by rsp4jack** [comment]
The only downside is GUI is integrated. I want to make the GUI independent, and GUI is a config editor.
Now Playing will read config file and do something like Now Playing Serato.
And I need to choose how does Now Playing Serato to make dependent, like dynamic-linking and static-linking.

**Comment by rsp4jack** [comment]
If select the "dynamic-linking" mode, I think Now Playing Serato to be a library is best.

**Comment by rsp4jack** [comment]
I think can use WebSocket to get info from Now Playing Serato.

**Comment by Fred-DTV** [comment]
amazing man!

the linking to the Serato library only works if OBS is running on the same computer. That's why the remote integration via the live playlist is so important, because most people use 2 different computers for live sets

**Comment by rsp4jack** [comment]
So, I think can use WebSocket to get info from Now Playing Serato, and Now Playing can get info from another computer in the same LAN.

**Comment by rsp4jack** [comment]
I'm trying to a version of Now Playing Serato with WebSocket support.

**Comment by Creepercdn** [comment]
I'm fail to add WebSocket support to Now Playing Serato.

**Comment by rsp4jack** [comment]
New version of Now Playing Serato works fine with OBS WebSocket. [aw-was-here/Now-Playing-Serato](https://github.com/aw-was-here/Now-Playing-Serato)
I think it is the best method.
