### ISSUE TITLE
win32api module missing

### ISSUE THREAD

**Issue by Konrad1374** [Creepercdn/now_playing#3]
Tried to set it up but with the manual python install it wouldnt upgrade the pip, asked to install python from MS store which i did. Problm is in the log, also OBS didnt display any properties in the description section.
[obs_scipt_log_20210427_152833.txt](https://github.com/Creepercdn/now_playing/files/6384881/obs_scipt_log_20210427_152833.txt)

**Comment by rsp4jack** [comment]
OBS need Python 3.6. Please ensure it first.

After that, install pywin32 to Python. Input command in Command Prompt:
```
"path\to\python.exe" -m pip install -U setuptools wheel pywin32
```

If Python notice "No module named pip", install pip.
If you don't know how to install pip, google it.

**Comment by Konrad1374** [comment]
Had to reinstall OBS to fix it. Now it works without error.

**Comment by rsp4jack** [comment]
If this problem fixed, please close it.
